const res = [
    "CONFIGURATION_ADMINISTRATION_ACCESS_RIGHTS_DELETE",
    "CONFIGURATION_ADMINISTRATION_ACCESS_RIGHTS_EDIT",
    "CONFIGURATION_ADMINISTRATION_ACCESS_RIGHTS_SAVE",
    "CONFIGURATION_ADMINISTRATION_ACCESS_RIGHTS_SEARCH",
    "CONFIGURATION_ADMINISTRATION_APPROVAL_SETTINGS_DELETE",
    "CONFIGURATION_ADMINISTRATION_APPROVAL_SETTINGS_EDIT", //done
    "CONFIGURATION_ADMINISTRATION_APPROVAL_SETTINGS_SAVE", //done
    "CONFIGURATION_ADMINISTRATION_APPROVAL_SETTINGS_SEARCH", //done
    "CONFIGURATION_ADMINISTRATION_MODULE_DELETE",
    "CONFIGURATION_ADMINISTRATION_MODULE_EDIT", //done
    "CONFIGURATION_ADMINISTRATION_MODULE_SAVE", //done
    "CONFIGURATION_ADMINISTRATION_MODULE_SEARCH",//done
    "CONFIGURATION_ADMINISTRATION_NOTIFICATION_SETTINGS_DELETE",
    "CONFIGURATION_ADMINISTRATION_NOTIFICATION_SETTINGS_EDIT",
    "CONFIGURATION_ADMINISTRATION_NOTIFICATION_SETTINGS_SAVE",
    "CONFIGURATION_ADMINISTRATION_NOTIFICATION_SETTINGS_SEARCH", //done
    "CONFIGURATION_ADMINISTRATION_ROLES_DELETE",
    "CONFIGURATION_ADMINISTRATION_ROLES_EDIT", //done
    "CONFIGURATION_ADMINISTRATION_ROLES_SAVE", //done
    "CONFIGURATION_ADMINISTRATION_ROLES_SEARCH", //done
    "CONFIGURATION_ADMINISTRATION_SUB_MODULE_DELETE",
    "CONFIGURATION_ADMINISTRATION_SUB_MODULE_EDIT", //done
    "CONFIGURATION_ADMINISTRATION_SUB_MODULE_ITEM_DELETE",
    "CONFIGURATION_ADMINISTRATION_SUB_MODULE_ITEM_EDIT", //done
    "CONFIGURATION_ADMINISTRATION_SUB_MODULE_ITEM_SAVE", //done
    "CONFIGURATION_ADMINISTRATION_SUB_MODULE_ITEM_SEARCH", //done
    "CONFIGURATION_ADMINISTRATION_SUB_MODULE_SAVE", //done
    "CONFIGURATION_ADMINISTRATION_SUB_MODULE_SEARCH", //done
    "CONFIGURATION_ADMINISTRATION_USERS_DELETE",
    "CONFIGURATION_ADMINISTRATION_USERS_EDIT", //done
    "CONFIGURATION_ADMINISTRATION_USERS_SAVE", //done
    "CONFIGURATION_ADMINISTRATION_USERS_SEARCH", //done
    "CONFIGURATION_ADMINISTRATION_WORKFLOW_ACTIONS_DELETE",
    "CONFIGURATION_ADMINISTRATION_WORKFLOW_ACTIONS_EDIT",
    "CONFIGURATION_ADMINISTRATION_WORKFLOW_ACTIONS_SAVE",
    "CONFIGURATION_ADMINISTRATION_WORKFLOW_ACTIONS_SEARCH",
    "CONFIGURATION_CONFIGURATION_BASE_DELETE",
    "CONFIGURATION_CONFIGURATION_BASE_EDIT", //done
    "CONFIGURATION_CONFIGURATION_BASE_PLANT_DELETE",
    "CONFIGURATION_CONFIGURATION_BASE_PLANT_EDIT", //done
    "CONFIGURATION_CONFIGURATION_BASE_PLANT_SAVE", //done
    "CONFIGURATION_CONFIGURATION_BASE_PLANT_SEARCH", //done
    "CONFIGURATION_CONFIGURATION_BASE_SAVE", //done
    "CONFIGURATION_CONFIGURATION_BASE_SEARCH", //done
    "CONFIGURATION_CONFIGURATION_COMPANY_DELETE",
    "CONFIGURATION_CONFIGURATION_COMPANY_EDIT", //done
    "CONFIGURATION_CONFIGURATION_COMPANY_SAVE", //done
    "CONFIGURATION_CONFIGURATION_COMPANY_SEARCH", //done
    "CONFIGURATION_CONFIGURATION_CURRENCY_DELETE",
    "CONFIGURATION_CONFIGURATION_CURRENCY_EDIT", //done
    "CONFIGURATION_CONFIGURATION_CURRENCY_SAVE", //done
    "CONFIGURATION_CONFIGURATION_CURRENCY_SEARCH", //done
    "CONFIGURATION_CONFIGURATION_EXTERNAL_COMPANY_DELETE",
    "CONFIGURATION_CONFIGURATION_EXTERNAL_COMPANY_EDIT", //done
    "CONFIGURATION_CONFIGURATION_EXTERNAL_COMPANY_SAVE", //done
    "CONFIGURATION_CONFIGURATION_EXTERNAL_COMPANY_SEARCH", //done
    "CONFIGURATION_CONFIGURATION_LOCATION_DELETE",
    "CONFIGURATION_CONFIGURATION_LOCATION_EDIT", //done
    "CONFIGURATION_CONFIGURATION_LOCATION_SAVE", //done
    "CONFIGURATION_CONFIGURATION_LOCATION_SEARCH", //done
    "CONFIGURATION_CONFIGURATION_MANUFACTURER_DELETE",
    "CONFIGURATION_CONFIGURATION_MANUFACTURER_EDIT", //done
    "CONFIGURATION_CONFIGURATION_MANUFACTURER_SAVE", //done
    "CONFIGURATION_CONFIGURATION_MANUFACTURER_SEARCH", //done
    "CONFIGURATION_CONFIGURATION_VENDOR_CAPABILITIES_DELETE",
    "CONFIGURATION_CONFIGURATION_VENDOR_CAPABILITIES_EDIT", //done
    "CONFIGURATION_CONFIGURATION_VENDOR_CAPABILITIES_SAVE", //done
    "CONFIGURATION_CONFIGURATION_VENDOR_CAPABILITIES_SEARCH", //done
    "MATERIAL_MANAGEMENT_COMPARATIVE_STATEMENT_APPROVED_CS_DELETE",
    "MATERIAL_MANAGEMENT_COMPARATIVE_STATEMENT_APPROVED_CS_EDIT",
    "MATERIAL_MANAGEMENT_COMPARATIVE_STATEMENT_APPROVED_CS_SAVE",
    "MATERIAL_MANAGEMENT_COMPARATIVE_STATEMENT_APPROVED_CS_SEARCH", //done
    "MATERIAL_MANAGEMENT_COMPARATIVE_STATEMENT_GENERATE_CS_DELETE",
    "MATERIAL_MANAGEMENT_COMPARATIVE_STATEMENT_GENERATE_CS_EDIT",
    "MATERIAL_MANAGEMENT_COMPARATIVE_STATEMENT_GENERATE_CS_SAVE", //done
    "MATERIAL_MANAGEMENT_COMPARATIVE_STATEMENT_GENERATE_CS_SEARCH",
    "MATERIAL_MANAGEMENT_COMPARATIVE_STATEMENT_PENDING_CS_DELETE",
    "MATERIAL_MANAGEMENT_COMPARATIVE_STATEMENT_PENDING_CS_EDIT",
    "MATERIAL_MANAGEMENT_COMPARATIVE_STATEMENT_PENDING_CS_SAVE",
    "MATERIAL_MANAGEMENT_COMPARATIVE_STATEMENT_PENDING_CS_SEARCH", //done
    "MATERIAL_MANAGEMENT_CONFIGURATION_SHIPMENT_PROVIDER_DELETE",
    "MATERIAL_MANAGEMENT_CONFIGURATION_SHIPMENT_PROVIDER_EDIT",
    "MATERIAL_MANAGEMENT_CONFIGURATION_SHIPMENT_PROVIDER_SAVE",
    "MATERIAL_MANAGEMENT_CONFIGURATION_SHIPMENT_PROVIDER_SEARCH",
    "MATERIAL_MANAGEMENT_CONFIGURATION_SUPPLIER_DELETE",
    "MATERIAL_MANAGEMENT_CONFIGURATION_SUPPLIER_EDIT",
    "MATERIAL_MANAGEMENT_CONFIGURATION_SUPPLIER_SAVE",
    "MATERIAL_MANAGEMENT_CONFIGURATION_SUPPLIER_SEARCH",
    "MATERIAL_MANAGEMENT_ORDER_PURCHASE_ORDER_DELETE",
    "MATERIAL_MANAGEMENT_ORDER_PURCHASE_ORDER_EDIT",
    "MATERIAL_MANAGEMENT_ORDER_PURCHASE_ORDER_SAVE",
    "MATERIAL_MANAGEMENT_ORDER_PURCHASE_ORDER_SEARCH",
    "MATERIAL_MANAGEMENT_QUOTE_REQUEST_APPROVED_RFQ_DELETE",
    "MATERIAL_MANAGEMENT_QUOTE_REQUEST_APPROVED_RFQ_EDIT",
    "MATERIAL_MANAGEMENT_QUOTE_REQUEST_APPROVED_RFQ_SAVE",
    "MATERIAL_MANAGEMENT_QUOTE_REQUEST_APPROVED_RFQ_SEARCH",
    "MATERIAL_MANAGEMENT_QUOTE_REQUEST_PENDING_RFQ_DELETE",
    "MATERIAL_MANAGEMENT_QUOTE_REQUEST_PENDING_RFQ_EDIT",
    "MATERIAL_MANAGEMENT_QUOTE_REQUEST_PENDING_RFQ_SAVE",
    "MATERIAL_MANAGEMENT_QUOTE_REQUEST_PENDING_RFQ_SEARCH",
    "MATERIAL_MANAGEMENT_QUOTE_REQUEST_QUOTATION_DELETE",
    "MATERIAL_MANAGEMENT_QUOTE_REQUEST_QUOTATION_EDIT",
    "MATERIAL_MANAGEMENT_QUOTE_REQUEST_QUOTATION_SAVE",
    "MATERIAL_MANAGEMENT_QUOTE_REQUEST_QUOTATION_SEARCH",
    "MATERIAL_MANAGEMENT_QUOTE_REQUEST_REQUEST_FOR_QUOTATION(RFQ)_DELETE",
    "MATERIAL_MANAGEMENT_QUOTE_REQUEST_REQUEST_FOR_QUOTATION(RFQ)_EDIT",
    "MATERIAL_MANAGEMENT_QUOTE_REQUEST_REQUEST_FOR_QUOTATION(RFQ)_SAVE",
    "MATERIAL_MANAGEMENT_QUOTE_REQUEST_REQUEST_FOR_QUOTATION(RFQ)_SEARCH",
    "PLANNING_AIRCRAFT_AIRCRAFTS_DELETE",
    "PLANNING_AIRCRAFT_AIRCRAFTS_EDIT",
    "PLANNING_AIRCRAFT_AIRCRAFTS_SAVE",
    "PLANNING_AIRCRAFT_AIRCRAFTS_SEARCH",
    "PLANNING_AIRCRAFT_BUILD_AIRCRAFT_DELETE",
    "PLANNING_AIRCRAFT_BUILD_AIRCRAFT_EDIT",
    "PLANNING_AIRCRAFT_BUILD_AIRCRAFT_SAVE",
    "PLANNING_AIRCRAFT_BUILD_AIRCRAFT_SEARCH",
    "PLANNING_AIRCRAFT_LOCATIONS_DELETE",
    "PLANNING_AIRCRAFT_LOCATIONS_EDIT",
    "PLANNING_AIRCRAFT_LOCATIONS_SAVE",
    "PLANNING_AIRCRAFT_LOCATIONS_SEARCH",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_AIRCRAFT_TASKS_DELETE",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_AIRCRAFT_TASKS_EDIT",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_AIRCRAFT_TASKS_SAVE",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_AIRCRAFT_TASKS_SEARCH",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_CONSUMABLE_PARTS_DELETE",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_CONSUMABLE_PARTS_EDIT",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_CONSUMABLE_PARTS_SAVE",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_CONSUMABLE_PARTS_SEARCH",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_MAINTENANCE_WORK_ORDERS_DELETE",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_MAINTENANCE_WORK_ORDERS_EDIT",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_MAINTENANCE_WORK_ORDERS_SAVE",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_MAINTENANCE_WORK_ORDERS_SEARCH",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_TASK_DONE_DELETE",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_TASK_DONE_EDIT",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_TASK_DONE_SAVE",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_TASK_DONE_SEARCH",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_TASK_FORECASTS_DELETE",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_TASK_FORECASTS_EDIT",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_TASK_FORECASTS_SAVE",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_TASK_FORECASTS_SEARCH",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_TASK_RECORDS_DELETE",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_TASK_RECORDS_EDIT",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_TASK_RECORDS_SAVE",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_TASK_RECORDS_SEARCH",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_TASK_TYPE_DELETE",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_TASK_TYPE_EDIT",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_TASK_TYPE_SAVE",
    "PLANNING_AIRCRAFT_MAINTENANCE_PROGRAM_TASK_TYPE_SEARCH",
    "PLANNING_AIRCRAFT_MODELS_DELETE",
    "PLANNING_AIRCRAFT_MODELS_EDIT",
    "PLANNING_AIRCRAFT_MODELS_SAVE",
    "PLANNING_AIRCRAFT_MODELS_SEARCH",
    "PLANNING_AIRCRAFT_MODEL_TREES_DELETE",
    "PLANNING_AIRCRAFT_MODEL_TREES_EDIT",
    "PLANNING_AIRCRAFT_MODEL_TREES_SAVE",
    "PLANNING_AIRCRAFT_MODEL_TREES_SEARCH",
    "PLANNING_AIRCRAFT_PARTS_DELETE",
    "PLANNING_AIRCRAFT_PARTS_EDIT",
    "PLANNING_AIRCRAFT_PARTS_SAVE",
    "PLANNING_AIRCRAFT_PARTS_SEARCH",
    "PLANNING_AIRCRAFT_POSITIONS_DELETE",
    "PLANNING_AIRCRAFT_POSITIONS_EDIT",
    "PLANNING_AIRCRAFT_POSITIONS_SAVE",
    "PLANNING_AIRCRAFT_POSITIONS_SEARCH",
    "PLANNING_AIRCRAFT_SEATING_CONFIGURATIONS_DELETE",
    "PLANNING_AIRCRAFT_SEATING_CONFIGURATIONS_EDIT",
    "PLANNING_AIRCRAFT_SEATING_CONFIGURATIONS_SAVE",
    "PLANNING_AIRCRAFT_SEATING_CONFIGURATIONS_SEARCH",
    "PLANNING_AIRCRAFT_TECHNICAL_LOG_ADD_MEL_DELETE",
    "PLANNING_AIRCRAFT_TECHNICAL_LOG_ADD_MEL_EDIT",
    "PLANNING_AIRCRAFT_TECHNICAL_LOG_ADD_MEL_SAVE",
    "PLANNING_AIRCRAFT_TECHNICAL_LOG_ADD_MEL_SEARCH",
    "PLANNING_AIRCRAFT_TECHNICAL_LOG_ATL_BOOKS_DELETE",
    "PLANNING_AIRCRAFT_TECHNICAL_LOG_ATL_BOOKS_EDIT",
    "PLANNING_AIRCRAFT_TECHNICAL_LOG_ATL_BOOKS_SAVE",
    "PLANNING_AIRCRAFT_TECHNICAL_LOG_ATL_BOOKS_SEARCH",
    "PLANNING_AIRCRAFT_TECHNICAL_LOG_ATL_DELETE",
    "PLANNING_AIRCRAFT_TECHNICAL_LOG_ATL_EDIT",
    "PLANNING_AIRCRAFT_TECHNICAL_LOG_ATL_SAVE",
    "PLANNING_AIRCRAFT_TECHNICAL_LOG_ATL_SEARCH",
    "PLANNING_AIRCRAFT_TECHNICAL_LOG_SIGNATURES_DELETE",
    "PLANNING_AIRCRAFT_TECHNICAL_LOG_SIGNATURES_EDIT",
    "PLANNING_AIRCRAFT_TECHNICAL_LOG_SIGNATURES_SAVE",
    "PLANNING_AIRCRAFT_TECHNICAL_LOG_SIGNATURES_SEARCH",
    "PLANNING_CHECK_A/C_CHECKS_DELETE",
    "PLANNING_CHECK_A/C_CHECKS_EDIT",
    "PLANNING_CHECK_A/C_CHECKS_SAVE",
    "PLANNING_CHECK_A/C_CHECKS_SEARCH",
    "PLANNING_CHECK_A/C_CHECK_INDEX_DELETE",
    "PLANNING_CHECK_A/C_CHECK_INDEX_EDIT",
    "PLANNING_CHECK_A/C_CHECK_INDEX_SAVE",
    "PLANNING_CHECK_A/C_CHECK_INDEX_SEARCH",
    "PLANNING_CHECK_CHECKS_DELETE",
    "PLANNING_CHECK_CHECKS_EDIT",
    "PLANNING_CHECK_CHECKS_SAVE",
    "PLANNING_CHECK_CHECKS_SEARCH",
    "PLANNING_CONFIGURATIONS_A/C_TYPE_DELETE",
    "PLANNING_CONFIGURATIONS_A/C_TYPE_EDIT",
    "PLANNING_CONFIGURATIONS_A/C_TYPE_SAVE",
    "PLANNING_CONFIGURATIONS_A/C_TYPE_SEARCH",
    "PLANNING_CONFIGURATIONS_AIRPORT_DELETE",
    "PLANNING_CONFIGURATIONS_AIRPORT_EDIT",
    "PLANNING_CONFIGURATIONS_AIRPORT_SAVE",
    "PLANNING_CONFIGURATIONS_AIRPORT_SEARCH",
    "PLANNING_CONFIGURATIONS_CABIN_(SEAT_TYPE)_DELETE",
    "PLANNING_CONFIGURATIONS_CABIN_(SEAT_TYPE)_EDIT",
    "PLANNING_CONFIGURATIONS_CABIN_(SEAT_TYPE)_SAVE",
    "PLANNING_CONFIGURATIONS_CABIN_(SEAT_TYPE)_SEARCH",
    "PLANNING_REPORTS_AIRCRAFT_COMPONENT_HISTORY_CARD_DELETE",
    "PLANNING_REPORTS_AIRCRAFT_COMPONENT_HISTORY_CARD_EDIT",
    "PLANNING_REPORTS_AIRCRAFT_COMPONENT_HISTORY_CARD_SAVE",
    "PLANNING_REPORTS_AIRCRAFT_COMPONENT_HISTORY_CARD_SEARCH",
    "PLANNING_REPORTS_AIRCRAFT_HARD_TIME_COMPONENT_STATUS_DELETE",
    "PLANNING_REPORTS_AIRCRAFT_HARD_TIME_COMPONENT_STATUS_EDIT",
    "PLANNING_REPORTS_AIRCRAFT_HARD_TIME_COMPONENT_STATUS_SAVE",
    "PLANNING_REPORTS_AIRCRAFT_HARD_TIME_COMPONENT_STATUS_SEARCH",
    "PLANNING_REPORTS_AIRCRAFT_MEL_AND_CDL_STATUS_DELETE",
    "PLANNING_REPORTS_AIRCRAFT_MEL_AND_CDL_STATUS_EDIT",
    "PLANNING_REPORTS_AIRCRAFT_MEL_AND_CDL_STATUS_SAVE",
    "PLANNING_REPORTS_AIRCRAFT_MEL_AND_CDL_STATUS_SEARCH",
    "PLANNING_REPORTS_AIRFRAME_&_APPLIANCE_AD_STATUS_DELETE",
    "PLANNING_REPORTS_AIRFRAME_&_APPLIANCE_AD_STATUS_EDIT",
    "PLANNING_REPORTS_AIRFRAME_&_APPLIANCE_AD_STATUS_SAVE",
    "PLANNING_REPORTS_AIRFRAME_&_APPLIANCE_AD_STATUS_SEARCH",
    "PLANNING_REPORTS_AIR_WORTHINESS_DIRECTIVE_DELETE",
    "PLANNING_REPORTS_AIR_WORTHINESS_DIRECTIVE_EDIT",
    "PLANNING_REPORTS_AIR_WORTHINESS_DIRECTIVE_SAVE",
    "PLANNING_REPORTS_AIR_WORTHINESS_DIRECTIVE_SEARCH",
    "PLANNING_REPORTS_AMP_STATUS_DELETE",
    "PLANNING_REPORTS_AMP_STATUS_EDIT",
    "PLANNING_REPORTS_AMP_STATUS_SAVE",
    "PLANNING_REPORTS_AMP_STATUS_SEARCH",
    "PLANNING_REPORTS_DAILY_FLYING_HOURS_&_CYCLES_DELETE",
    "PLANNING_REPORTS_DAILY_FLYING_HOURS_&_CYCLES_EDIT",
    "PLANNING_REPORTS_DAILY_FLYING_HOURS_&_CYCLES_SAVE",
    "PLANNING_REPORTS_DAILY_FLYING_HOURS_&_CYCLES_SEARCH",
    "PLANNING_REPORTS_ENGINE_AD_STATUS_DELETE",
    "PLANNING_REPORTS_ENGINE_AD_STATUS_EDIT",
    "PLANNING_REPORTS_ENGINE_AD_STATUS_SAVE",
    "PLANNING_REPORTS_ENGINE_AD_STATUS_SEARCH",
    "PLANNING_REPORTS_ENGINE_LLPS_STATUS_DELETE",
    "PLANNING_REPORTS_ENGINE_LLPS_STATUS_EDIT",
    "PLANNING_REPORTS_ENGINE_LLPS_STATUS_SAVE",
    "PLANNING_REPORTS_ENGINE_LLPS_STATUS_SEARCH",
    "PLANNING_REPORTS_INSPECTION_CONTROL_CARD_DELETE",
    "PLANNING_REPORTS_INSPECTION_CONTROL_CARD_EDIT",
    "PLANNING_REPORTS_INSPECTION_CONTROL_CARD_SAVE",
    "PLANNING_REPORTS_INSPECTION_CONTROL_CARD_SEARCH",
    "PLANNING_REPORTS_MAN_HOURS_DELETE",
    "PLANNING_REPORTS_MAN_HOURS_EDIT",
    "PLANNING_REPORTS_MAN_HOURS_SAVE",
    "PLANNING_REPORTS_MAN_HOURS_SEARCH",
    "PLANNING_REPORTS_NRC_CONTROL_LIST_DELETE",
    "PLANNING_REPORTS_NRC_CONTROL_LIST_EDIT",
    "PLANNING_REPORTS_NRC_CONTROL_LIST_SAVE",
    "PLANNING_REPORTS_NRC_CONTROL_LIST_SEARCH",
    "PLANNING_REPORTS_OIL_UPLIFT_REPORT_DELETE",
    "PLANNING_REPORTS_OIL_UPLIFT_REPORT_EDIT",
    "PLANNING_REPORTS_OIL_UPLIFT_REPORT_SAVE",
    "PLANNING_REPORTS_OIL_UPLIFT_REPORT_SEARCH",
    "PLANNING_REPORTS_ON_CONDITION_COMPONENTS_LIST_DELETE",
    "PLANNING_REPORTS_ON_CONDITION_COMPONENTS_LIST_EDIT",
    "PLANNING_REPORTS_ON_CONDITION_COMPONENTS_LIST_SAVE",
    "PLANNING_REPORTS_ON_CONDITION_COMPONENTS_LIST_SEARCH",
    "PLANNING_REPORTS_PROPELLER_STATUS_DELETE",
    "PLANNING_REPORTS_PROPELLER_STATUS_EDIT",
    "PLANNING_REPORTS_PROPELLER_STATUS_SAVE",
    "PLANNING_REPORTS_PROPELLER_STATUS_SEARCH",
    "PLANNING_REPORTS_SECTOR-WISE_UTILIZATION_DELETE",
    "PLANNING_REPORTS_SECTOR-WISE_UTILIZATION_EDIT",
    "PLANNING_REPORTS_SECTOR-WISE_UTILIZATION_SAVE",
    "PLANNING_REPORTS_SECTOR-WISE_UTILIZATION_SEARCH",
    "PLANNING_REPORTS_SERVICE_BULLETIN_LIST_DELETE",
    "PLANNING_REPORTS_SERVICE_BULLETIN_LIST_EDIT",
    "PLANNING_REPORTS_SERVICE_BULLETIN_LIST_SAVE",
    "PLANNING_REPORTS_SERVICE_BULLETIN_LIST_SEARCH",
    "PLANNING_REPORTS_STC_AND_MOD_STATUST_DELETE",
    "PLANNING_REPORTS_STC_AND_MOD_STATUST_EDIT",
    "PLANNING_REPORTS_STC_AND_MOD_STATUST_SAVE",
    "PLANNING_REPORTS_STC_AND_MOD_STATUST_SEARCH",
    "PLANNING_REPORTS_WORK_PACKAGE_CERTIFICATION_RECORD_DELETE",
    "PLANNING_REPORTS_WORK_PACKAGE_CERTIFICATION_RECORD_EDIT",
    "PLANNING_REPORTS_WORK_PACKAGE_CERTIFICATION_RECORD_SAVE",
    "PLANNING_REPORTS_WORK_PACKAGE_CERTIFICATION_RECORD_SEARCH",
    "PLANNING_REPORTS_WORK_PACKAGE_SUMMARY_DELETE",
    "PLANNING_REPORTS_WORK_PACKAGE_SUMMARY_EDIT",
    "PLANNING_REPORTS_WORK_PACKAGE_SUMMARY_SAVE",
    "PLANNING_REPORTS_WORK_PACKAGE_SUMMARY_SEARCH",
    "PLANNING_REPORTS_WORK_PACKAGE_TASK_INDEX_DELETE",
    "PLANNING_REPORTS_WORK_PACKAGE_TASK_INDEX_EDIT",
    "PLANNING_REPORTS_WORK_PACKAGE_TASK_INDEX_SAVE",
    "PLANNING_REPORTS_WORK_PACKAGE_TASK_INDEX_SEARCH",
    "PLANNING_REPORTS_WORK_SCOPE_APPROVAL_DELETE",
    "PLANNING_REPORTS_WORK_SCOPE_APPROVAL_EDIT",
    "PLANNING_REPORTS_WORK_SCOPE_APPROVAL_SAVE",
    "PLANNING_REPORTS_WORK_SCOPE_APPROVAL_SEARCH",
    "QUALITY_MANUFACTURER_APPROVED_LIST_DELETE",
    "QUALITY_MANUFACTURER_APPROVED_LIST_EDIT",
    "QUALITY_MANUFACTURER_APPROVED_LIST_SAVE",
    "QUALITY_MANUFACTURER_APPROVED_LIST_SEARCH", //done
    "QUALITY_MANUFACTURER_PENDING_LIST_DELETE",
    "QUALITY_MANUFACTURER_PENDING_LIST_EDIT",
    "QUALITY_MANUFACTURER_PENDING_LIST_SAVE",
    "QUALITY_MANUFACTURER_PENDING_LIST_SEARCH", //done
    "STORE_INSPECTOR_INSPECTION_CHECKLIST_APPROVED_INSPECTION_CHECKLIST_DELETE",
    "STORE_INSPECTOR_INSPECTION_CHECKLIST_APPROVED_INSPECTION_CHECKLIST_EDIT",
    "STORE_INSPECTOR_INSPECTION_CHECKLIST_APPROVED_INSPECTION_CHECKLIST_SAVE",
    "STORE_INSPECTOR_INSPECTION_CHECKLIST_APPROVED_INSPECTION_CHECKLIST_SEARCH", //done
    "STORE_INSPECTOR_INSPECTION_CHECKLIST_INSPECTION_CHECKLIST_DELETE",
    "STORE_INSPECTOR_INSPECTION_CHECKLIST_INSPECTION_CHECKLIST_EDIT", //done
    "STORE_INSPECTOR_INSPECTION_CHECKLIST_INSPECTION_CHECKLIST_SAVE", //done
    "STORE_INSPECTOR_INSPECTION_CHECKLIST_INSPECTION_CHECKLIST_SEARCH",
    "STORE_INSPECTOR_INSPECTION_CHECKLIST_PENDING_INSPECTION_CHECKLIST_DELETE",
    "STORE_INSPECTOR_INSPECTION_CHECKLIST_PENDING_INSPECTION_CHECKLIST_EDIT",
    "STORE_INSPECTOR_INSPECTION_CHECKLIST_PENDING_INSPECTION_CHECKLIST_SAVE",
    "STORE_INSPECTOR_INSPECTION_CHECKLIST_PENDING_INSPECTION_CHECKLIST_SEARCH", //done
    "STORE_INSPECTOR_STORE_INSPECTOR_STORE_INSPECTION_DELETE",
    "STORE_INSPECTOR_STORE_INSPECTOR_STORE_INSPECTION_EDIT", //done
    "STORE_INSPECTOR_STORE_INSPECTOR_STORE_INSPECTION_SAVE", //done
    "STORE_INSPECTOR_STORE_INSPECTOR_STORE_INSPECTION_SEARCH", //done
    "STORE_PARTS_DEMAND_APPROVED_DEMAND_DELETE",
    "STORE_PARTS_DEMAND_APPROVED_DEMAND_EDIT",
    "STORE_PARTS_DEMAND_APPROVED_DEMAND_SAVE",
    "STORE_PARTS_DEMAND_APPROVED_DEMAND_SEARCH",
    "STORE_PARTS_DEMAND_DEMAND_REPORT_DELETE",
    "STORE_PARTS_DEMAND_DEMAND_REPORT_EDIT",
    "STORE_PARTS_DEMAND_DEMAND_REPORT_SAVE",
    "STORE_PARTS_DEMAND_DEMAND_REPORT_SEARCH",
    "STORE_PARTS_DEMAND_PENDING_DEMAND_DELETE",
    "STORE_PARTS_DEMAND_PENDING_DEMAND_EDIT",
    "STORE_PARTS_DEMAND_PENDING_DEMAND_SAVE",
    "STORE_PARTS_DEMAND_PENDING_DEMAND_SEARCH",
    "STORE_PARTS_DEMAND_STORE_DEMAND_DELETE",
    "STORE_PARTS_DEMAND_STORE_DEMAND_EDIT",
    "STORE_PARTS_DEMAND_STORE_DEMAND_SAVE", //done
    "STORE_PARTS_DEMAND_STORE_DEMAND_SEARCH", //done
    "STORE_PARTS_ISSUE_APPROVED_ISSUES_DELETE",
    "STORE_PARTS_ISSUE_APPROVED_ISSUES_EDIT",
    "STORE_PARTS_ISSUE_APPROVED_ISSUES_SAVE",
    "STORE_PARTS_ISSUE_APPROVED_ISSUES_SEARCH",
    "STORE_PARTS_ISSUE_ISSUE_DEMAND_DELETE",
    "STORE_PARTS_ISSUE_ISSUE_DEMAND_EDIT",
    "STORE_PARTS_ISSUE_ISSUE_DEMAND_SAVE",
    "STORE_PARTS_ISSUE_ISSUE_DEMAND_SEARCH",
    "STORE_PARTS_ISSUE_ISSUE_REPORT_DELETE",
    "STORE_PARTS_ISSUE_ISSUE_REPORT_EDIT",
    "STORE_PARTS_ISSUE_ISSUE_REPORT_SAVE",
    "STORE_PARTS_ISSUE_ISSUE_REPORT_SEARCH",
    "STORE_PARTS_ISSUE_PENDING_ISSUES_DELETE",
    "STORE_PARTS_ISSUE_PENDING_ISSUES_EDIT",
    "STORE_PARTS_ISSUE_PENDING_ISSUES_SAVE",
    "STORE_PARTS_ISSUE_PENDING_ISSUES_SEARCH",
    "STORE_PARTS_REQUISITION_APPROVED_MATERIAL_MANAGEMENT_REQUISITION_DELETE",
    "STORE_PARTS_REQUISITION_APPROVED_MATERIAL_MANAGEMENT_REQUISITION_EDIT",
    "STORE_PARTS_REQUISITION_APPROVED_MATERIAL_MANAGEMENT_REQUISITION_SAVE",
    "STORE_PARTS_REQUISITION_APPROVED_MATERIAL_MANAGEMENT_REQUISITION_SEARCH",
    "STORE_PARTS_REQUISITION_MATERIAL_MANAGEMENT_REQUISITION_DELETE",
    "STORE_PARTS_REQUISITION_MATERIAL_MANAGEMENT_REQUISITION_EDIT",
    "STORE_PARTS_REQUISITION_MATERIAL_MANAGEMENT_REQUISITION_REPORT_DELETE",
    "STORE_PARTS_REQUISITION_MATERIAL_MANAGEMENT_REQUISITION_REPORT_EDIT",
    "STORE_PARTS_REQUISITION_MATERIAL_MANAGEMENT_REQUISITION_REPORT_SAVE",
    "STORE_PARTS_REQUISITION_MATERIAL_MANAGEMENT_REQUISITION_REPORT_SEARCH",
    "STORE_PARTS_REQUISITION_MATERIAL_MANAGEMENT_REQUISITION_SAVE", //done
    "STORE_PARTS_REQUISITION_MATERIAL_MANAGEMENT_REQUISITION_SEARCH",
    "STORE_PARTS_REQUISITION_PENDING_MATERIAL_MANAGEMENT_REQUISITION_DELETE",
    "STORE_PARTS_REQUISITION_PENDING_MATERIAL_MANAGEMENT_REQUISITION_EDIT",
    "STORE_PARTS_REQUISITION_PENDING_MATERIAL_MANAGEMENT_REQUISITION_SAVE",
    "STORE_PARTS_REQUISITION_PENDING_MATERIAL_MANAGEMENT_REQUISITION_SEARCH",
    "STORE_PARTS_RETURN_APPROVED_PARTS_RETURN_DELETE",
    "STORE_PARTS_RETURN_APPROVED_PARTS_RETURN_EDIT",
    "STORE_PARTS_RETURN_APPROVED_PARTS_RETURN_SAVE",
    "STORE_PARTS_RETURN_APPROVED_PARTS_RETURN_SEARCH",//done
    "STORE_PARTS_RETURN_PARTS_RETURN_DELETE",
    "STORE_PARTS_RETURN_PARTS_RETURN_EDIT",//done
    "STORE_PARTS_RETURN_PARTS_RETURN_SAVE",//done
    "STORE_PARTS_RETURN_PARTS_RETURN_SEARCH",
    "STORE_PARTS_RETURN_PENDING_PARTS_RETURN_DELETE",
    "STORE_PARTS_RETURN_PENDING_PARTS_RETURN_EDIT",
    "STORE_PARTS_RETURN_PENDING_PARTS_RETURN_SAVE",
    "STORE_PARTS_RETURN_PENDING_PARTS_RETURN_SEARCH",//done
    "STORE_SCRAP_PARTS_SCRAP_PARTS_DELETE",
    "STORE_SCRAP_PARTS_SCRAP_PARTS_EDIT",//done
    "STORE_SCRAP_PARTS_SCRAP_PARTS_SAVE",//done
    "STORE_SCRAP_PARTS_SCRAP_PART_SEARCH",//done
    "STORE_STORE_CONFIGURATION_RACK_DELETE",
    "STORE_STORE_CONFIGURATION_RACK_EDIT",
    "STORE_STORE_CONFIGURATION_RACK_ROW_BIN_DELETE",
    "STORE_STORE_CONFIGURATION_RACK_ROW_BIN_EDIT",
    "STORE_STORE_CONFIGURATION_RACK_ROW_BIN_SAVE",
    "STORE_STORE_CONFIGURATION_RACK_ROW_BIN_SEARCH",
    "STORE_STORE_CONFIGURATION_RACK_ROW_DELETE",
    "STORE_STORE_CONFIGURATION_RACK_ROW_EDIT",
    "STORE_STORE_CONFIGURATION_RACK_ROW_SAVE",
    "STORE_STORE_CONFIGURATION_RACK_ROW_SEARCH",
    "STORE_STORE_CONFIGURATION_RACK_SAVE",
    "STORE_STORE_CONFIGURATION_RACK_SEARCH",
    "STORE_STORE_CONFIGURATION_ROOM_DELETE",
    "STORE_STORE_CONFIGURATION_ROOM_EDIT",
    "STORE_STORE_CONFIGURATION_ROOM_SAVE",
    "STORE_STORE_CONFIGURATION_ROOM_SEARCH",
    "STORE_STORE_CONFIGURATION_STOCK_ROOM_DELETE",
    "STORE_STORE_CONFIGURATION_STOCK_ROOM_EDIT", //done
    "STORE_STORE_CONFIGURATION_STOCK_ROOM_SAVE", //done
    "STORE_STORE_CONFIGURATION_STOCK_ROOM_SEARCH", //done
    "STORE_STORE_CONFIGURATION_TECHNICAL_STORE_DELETE",
    "STORE_STORE_CONFIGURATION_TECHNICAL_STORE_EDIT",
    "STORE_STORE_CONFIGURATION_TECHNICAL_STORE_SAVE",
    "STORE_STORE_CONFIGURATION_TECHNICAL_STORE_SEARCH",
    "STORE_STORE_CONFIGURATION_UNIT_OF_MEASUREMENT_DELETE",
    "STORE_STORE_CONFIGURATION_UNIT_OF_MEASUREMENT_EDIT", //done
    "STORE_STORE_CONFIGURATION_UNIT_OF_MEASUREMENT_SAVE", //done
    "STORE_STORE_CONFIGURATION_UNIT_OF_MEASUREMENT_SEARCH", //done
    "STORE_STORE_PARTS_AVAILABILITY_PARTS_AVAILABILITY_DELETE",
    "STORE_STORE_PARTS_AVAILABILITY_PARTS_AVAILABILITY_EDIT",
    "STORE_STORE_PARTS_AVAILABILITY_PARTS_AVAILABILITY_SAVE", //done
    "STORE_STORE_PARTS_AVAILABILITY_PARTS_AVAILABILITY_SEARCH", //done
    "STORE_STORE_PARTS_AVAILABILITY_STORE_PARTS_DELETE",
    "STORE_STORE_PARTS_AVAILABILITY_STORE_PARTS_EDIT",
    "STORE_STORE_PARTS_AVAILABILITY_STORE_PARTS_SAVE",
    "STORE_STORE_PARTS_AVAILABILITY_STORE_PARTS_SEARCH",
    "STORE_UNSERVICEABLE_ITEM_UNSERVICEABLE_ITEM_DELETE",
    "STORE_UNSERVICEABLE_ITEM_UNSERVICEABLE_ITEM_EDIT",//done
    "STORE_UNSERVICEABLE_ITEM_UNSERVICEABLE_ITEM_SAVE",//done
    "STORE_UNSERVICEABLE_ITEM_UNSERVICEABLE_ITEM_SEARCH"//done
]

const DONE_LIST = [
    {
        STORE: [
            'PARTS DEMAND',
            'PARTS REQUISITION',
            'PARTS ISSUE',
            'UNSERVICEABLE ITEM',
            'SCRAP PARTS',
            'PARTS RETURN',
            'STORE PARTS AVAILABILITY',
            {
                'STORE_CONFIGURATION': [
                    'Unit Of Measurement',
                    'Stock Room',
                    'Rack row Bin',
                    'Rack row',
                    'Rack',
                    'Room',
                    'Technical store'
                ]
            }
        ],
    },
    {
        MATERIAL_MANAGEMENT: [
            'QUOTE_REQUEST',
            'COMPARATIVE_STATEMENT',
            'SUPPLIER',
            'PURCHASE_ORDER',
        ]
    },
    {
        CONFIGURATION : [
            'BASE_PLANT',
            'BASE',
            'LOCATION',
            'COMPANY',
            'MANUFACTURER',
            'EXTERNAL_COMPANY',
            'CURRENCY',
            'VENDOR_CAPABILITIES',
            {
                'ADMINISTRATION' : [
                    'USERS',
                    'ROLE',
                    'MODULE',
                    'WORKFLOW_ACTIONS',
                    'APPROVAL_SETTINGS',
                    'NOTIFICATION_SETTINGS',
                    'ACCESS_RIGHTS'
                ]
            }
        ]
    },
    {
        QUALITY: [
           'MANUFACTURER',
        ],
    },
    {
        STORE_INSPECTOR: [
           'STORE_INSPECTION',
            {
                INSPECTION_CHECKLIST : [
                    'INSPECTION_CHECKLIST',
                    'PENDING_INSPECTION_CHECKLIST',
                    'APPROVED_INSPECTION_CHECKLIST'
                ]
            }
        ]
    }
]

const PERMISSION_NOT_DEFINED = [
    'WORK_ORDER',
    'STORE_SERIAL',
    'MATERIAL_MANAGEMENT: ORDER -> PURCHASE_ORDER',
    'PARTS_RECEIVE',
    'NOTIFICATION_SETTINGS', // NOT DONE YET
    'AUDIT -> COMPARATIVE_STATEMENT', // NOT WORKING NOW FOR THIS PERMISSION BRANCH
    'SHIPMENT_PROVIDER_RFQ'

]
console.log(PERMISSION_NOT_DEFINED)